Fix C++ build on Windows with VC++
The change to enc2xs follows from this thread:
http://www.nntp.perl.org/group/perl.perl5.porters/2015/01/msg224875.html

The change to Encode.xs is to fix errors in the Encode.c compilation
which results from the enc2xs change (now that we specify "C" linkage, the
header file cannot be #included within { }):
c:\dev\git\perl\cpan\encode\def_t.h(7) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(7) : error C2512: 'encode_s' : no appropriate default constructor available
c:\dev\git\perl\cpan\encode\def_t.h(8) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(8) : error C2512: 'encode_s' : no appropriate default constructor available
c:\dev\git\perl\cpan\encode\def_t.h(9) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(9) : error C2512: 'encode_s' : no appropriate default constructor available
c:\dev\git\perl\cpan\encode\def_t.h(10) : error C2598: linkage specification must be at global scope
c:\dev\git\perl\cpan\encode\def_t.h(10) : error C2512: 'encode_s' : no appropriate default constructor available