Fix loading Encode::Alias before Encode
Calling

  use Encode::Alias;

cased error:

  Undefined subroutine &Encode::define_alias called at lib/Encode.pm line 102.
  Compilation failed in require at lib/Encode/Alias.pm line 7.
  BEGIN failed--compilation aborted at lib/Encode/Alias.pm line 7.
  Compilation failed in require at -e line 1.
  BEGIN failed--compilation aborted at -e line 1.

Fixes #116